### adding new card
POST http://localhost:8080/addcard
Accept: application/json
Content-Type: application/json

{
  "userId": 1,
  "cardName": "Banco Sol",
  "cardNumber": 44444444,
  "expirationYear": 2024,
  "expirationMonth": 4,
  "cvc": 2222,
  "creationDate": "2021-12-31T16:00:00Z",
  "status": 1
}

### get card list by user
GET http://localhost:8080/user/2/listCards
Accept: application/json

### get card list by user
GET http://localhost:8080/card/1
Accept: application/json

### update card
PUT  http://localhost:8080/updateCard
Accept: application/json
Content-Type: application/json

{
  "cardId": 1,
  "userId": 1,
  "cardName": "Banco Nacional",
  "cardNumber": 12345678,
  "expirationYear": 2022,
  "expirationMonth": 6,
  "cvc": 1234,
  "creationDate": "2021-03-07",
  "status": 1
}


### delete card
DELETE http://localhost:8080/card/5
Accept: application/json