### adding new manager
POST http://localhost:8080/manager/register/new
Accept: application/json
Content-Type: application/json

{
  "name": "Joel",
  "surname": "Guzman",
  "username": "Joel",
  "userPhoto": "https://res.cloudinary.com/fulano/image/upload/v1617116017/profileimage_kptkl6.jpg",
  "gender": "Male",
  "email": "joelguz@gmail.com",
  "description": "Multiple congenital anomalies, so described",
  "cellphone": "7845139010",
  "password": "12345678"
}

### Login manager
POST http://localhost:8080/manager/login
Accept: application/json
Content-Type: application/json

{
  "username": "jscatchard1",
  "password": "yokcVYP4"
}

### Auth (Only testing)
GET http://localhost:8080/manager/login/530
Accept: application/json
Content-Type: application/json