### get product offers
GET http://localhost:8080/offer/product/162
Accept: application/json

### Create offer
POST http://localhost:8080/offer/new
Accept: application/json
Content-Type: application/json

{
  "productId": 519,
  "percentage": 60,
  "startDate": "2021-12-02T02:50:12.208Z",
  "endDate": "2021-12-02T02:50:12.208Z",
  "status": 1
}

### Update offer by product id
PUT http://localhost:8080/offer/update
Accept: application/json
Content-Type: application/json

{
  "productId": 519,
  "offerId": 512,
  "percentage": 90,
  "startDate": "2021-11-02T02:50:12.208Z",
  "endDate": "2021-11-02T02:50:12.208Z",
  "status": 1
}


### Delete offer by offer id
DELETE http://localhost:8080/offer/delete/85
