### get product offers
GET http://localhost:8080/offer/product/162
Accept: application/json

### get product offers by branch
GET http://localhost:8080/offer/product/branch/4
Accept: application/json

### Create offer
POST http://localhost:8080/offer/new
Accept: application/json
Content-Type: application/json

{
  "productId": 162,
  "percentage": 60,
  "startDate": "2021-12-02",
  "endDate": "2021-12-02",
  "status": 1
}

### Update offer by product id
PUT http://localhost:8080/offer/update
Accept: application/json
Content-Type: application/json

{
  "productId": 162,
  "offerId": 532,
  "percentage": 90,
  "startDate": "2021-11-10",
  "endDate": "2021-11-10",
  "status": 1
}


### Delete offer by offer id
DELETE http://localhost:8080/offer/delete/85
