### get product list by managerid (Frontend web)
GET http://localhost:8080/manager/530/products?page=1&size=10
Accept: application/json

### get product list by branchId (Frontend movil)
GET http://localhost:8080/user/1/branchOffice/1
Accept: application/json

### get product list by userid and branch office id and category id (Frontend movil)
GET http://localhost:8080/user/1/branchOffice/1/category/2
Accept: application/json

### adding new product with adminid and branch office id
POST http://localhost:8080/admin/3/branchOffice/1/product
Accept: application/json
Content-Type: application/json

{
  "name": "Piña",
  "price": "30.00",
  "description": "Fruta color amarillo",
  "unit": "10",
  "category": "Abarrotes",
  "offer": {
    "name": "offer 1",
    "percentage": 50,
    "startDate": "2021-11-02T02:50:12.208Z",
    "endDate": "2021-11-02T02:50:12.208Z",
    "imageUrl": "url"
  },
  "imagesUrl": [
    "https://res.cloudinary.com/fulano/image/upload/v1617490236/img_default_ywgnfs.jpg",
    "https://res.cloudinary.com/fulano/image/upload/v1617490323/img_default1_cuuu1t.jpg",
    "https://res.cloudinary.com/fulano/image/upload/v1617490329/img_default3_lrczpl.jpg"
  ]
}

### get product details
GET http://localhost:8080/product/1008
Accept: application/json

### delete product
DELETE http://localhost:8080/product/10
Accept: application/json

### get product offers
GET http://localhost:8080/product/offers/3
Accept: application/json

### search products
GET http://localhost:8080/product/branchOffice/2/search/S?page=1&size=5
Accept: application/json

### pagination
GET http://localhost:8080/product?page=1&size=10
Accept: application/json

### Update product
PUT http://localhost:8080/product/update/1008
Accept: application/json
Content-Type: application/json

{
  "name": "Zanahoria",
  "price": "30.00",
  "description": "Fruta color amarillo",
  "unit": "10",
  "category": "Abarrotes",
  "imagesUrl": [
    "https://res.cloudinary.com/fulano/image/upload/v1617490236/img_default_ywgnfs.jpg",
    "https://res.cloudinary.com/fulano/image/upload/v1617490323/img_default1_cuuu1t.jpg",
    "https://res.cloudinary.com/fulano/image/upload/v1617490329/img_default3_lrczpl.jpg"
  ]
}

### update product with manager and branch office id
PUT http://localhost:8080/manager/530/product/162
Accept: application/json
Content-Type: application/json

{
  "name": "Zanahoria",
  "price": "30.00",
  "description": "Fruta color amarillo",
  "unit": "10",
  "category": "Abarrotes",
  "imagesUrl": [
    "https://res.cloudinary.com/fulano/image/upload/v1617490236/img_default_ywgnfs.jpg",
    "https://res.cloudinary.com/fulano/image/upload/v1617490323/img_default1_cuuu1t.jpg",
    "https://res.cloudinary.com/fulano/image/upload/v1617490329/img_default3_lrczpl.jpg"
  ]
}