### get product list by userid and branch office id
GET http://localhost:8080/user/1/branchOffice/6/product
Accept: application/json

### adding new product with adminid and branch office id
POST http://localhost:8080/admin/1/branchOffice/1/product
Accept: application/json
Content-Type: application/json

{
  "name": "Tomate",
  "price": "20.00",
  "description": "Verdura color rojo",
  "unit": "10",
  "category": "verdura",
  "offer": {
    "name": "offer 1",
    "percentage": 10,
    "startDate": "19-02-2020",
    "endDate": "19-04-2020",
    "imageUrl": "url"
  },
  "imagesUrl": [
    {"photo": "Url 1"},
    {"photo": "Url 2"}
  ]
}

### get product details
GET http://localhost:8080/product/10
Accept: application/json

### get product details
DELETE http://localhost:8080/product/10
Accept: application/json