### Purchase event
POST http://localhost:8080/purchase/user/1
Accept: application/json
Content-Type: application/json

{
  "productPurchases": [
    {
      "productId": 1,
      "price": 50,
      "unit": 2
    }
  ],
  "billingAddress": "xxxxxx",
  "city": "La Paz",
  "cardId": 1
}