### adding new user
POST http://localhost:8080/user
Accept: application/json
Content-Type: application/json

{
  "name": "Joselito",
  "surname": "Vaca",
  "username": "prueba",
  "gender": "Male",
  "userPhoto": "https://res.cloudinary.com/fulano/image/upload/v1617116017/profileimage_kptkl6.jpg",
  "email": "josevaca@gmail.com",
  "password": "12345678"
}

### Get list of users
GET http://localhost:8080/user/list
Accept: application/json

### user login
POST http://localhost:8080/user/login
Accept: application/json
Content-Type: application/json

{
  "username": "cewbach0",
  "password": "WzUEgwCE"
}

### Get user by id
GET http://localhost:8080/user/1
Accept: application/json

### Enable or disable user by user id
PUT http://localhost:8080/user/status/1
Accept: application/json